# Generated by Django 3.1.12 on 2024-12-24 17:16

import account.models
import bson.objectid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('channel_name', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('views', models.BigIntegerField()),
                ('upload_date', models.DateTimeField()),
                ('url', models.URLField(unique=True)),
                ('channel', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, null=True)),
                ('likes', models.BigIntegerField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('comments', djongo.models.fields.ArrayField(blank=True, default=list, model_container=account.models.YouTubeComment)),
                ('transcript', djongo.models.fields.ArrayField(blank=True, default=list, model_container=account.models.Transcript)),
            ],
            options={
                'db_table': 'chart',
            },
        ),
        migrations.CreateModel(
            name='ChartDuplicateVideo',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('url', models.URLField(unique=True)),
                ('views', models.BigIntegerField()),
                ('upload_date', models.DateTimeField()),
                ('channel_name', models.CharField(max_length=255)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('likes', models.BigIntegerField(blank=True, null=True)),
                ('transcript', djongo.models.fields.ArrayField(blank=True, default=list, model_container=account.models.TranscriptItem)),
            ],
            options={
                'db_table': 'chart_duplicate_videos',
            },
        ),
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('rating', models.PositiveBigIntegerField()),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'feedbacks',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyIssue',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('views', models.BigIntegerField()),
                ('upload_date', models.DateTimeField()),
                ('url', models.URLField(unique=True)),
                ('channel', models.CharField(max_length=255)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('comments', djongo.models.fields.ArrayField(blank=True, default=list, model_container=account.models.YouTubeComment)),
                ('transcript', djongo.models.fields.ArrayField(blank=True, default=list, model_container=account.models.Transcript)),
                ('desc', models.TextField(blank=True, null=True)),
                ('likes', models.BigIntegerField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'weekly_issues',
            },
        ),
        migrations.CreateModel(
            name='WeeklyIssueDuplicateVideo',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('url', models.URLField(unique=True)),
                ('views', models.BigIntegerField()),
                ('upload_date', models.DateTimeField()),
                ('channel_name', models.CharField(max_length=255)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('likes', models.BigIntegerField(blank=True, null=True)),
                ('transcript', djongo.models.fields.ArrayField(blank=True, default=list, model_container=account.models.TranscriptItem)),
            ],
            options={
                'db_table': 'weekly_issue_duplicate_videos',
            },
        ),
        migrations.CreateModel(
            name='YouTubeData',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('views', models.BigIntegerField()),
                ('upload_date', models.DateTimeField()),
                ('url', models.URLField(unique=True)),
                ('channel', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, null=True)),
                ('likes', models.BigIntegerField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('comments', djongo.models.fields.ArrayField(blank=True, default=list, model_container=account.models.YouTubeComment)),
                ('transcript', djongo.models.fields.ArrayField(blank=True, default=list, model_container=account.models.Transcript)),
            ],
            options={
                'db_table': 'youtube_datas',
            },
        ),
        migrations.AddIndex(
            model_name='weeklyissueduplicatevideo',
            index=models.Index(fields=['title'], name='weekly_issu_title_eb47a7_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyissueduplicatevideo',
            index=models.Index(fields=['upload_date'], name='weekly_issu_upload__efea35_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyissueduplicatevideo',
            index=models.Index(fields=['channel_name'], name='weekly_issu_channel_124d38_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyissue',
            index=models.Index(fields=['title'], name='weekly_issu_title_585d95_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyissue',
            index=models.Index(fields=['url'], name='weekly_issu_url_4dfe33_idx'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='youtube_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.youtubedata'),
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chartduplicatevideo',
            index=models.Index(fields=['title'], name='chart_dupli_title_315009_idx'),
        ),
        migrations.AddIndex(
            model_name='chartduplicatevideo',
            index=models.Index(fields=['upload_date'], name='chart_dupli_upload__e88ee1_idx'),
        ),
        migrations.AddIndex(
            model_name='chartduplicatevideo',
            index=models.Index(fields=['views'], name='chart_dupli_views_a83957_idx'),
        ),
        migrations.AddIndex(
            model_name='chart',
            index=models.Index(fields=['title'], name='chart_title_374973_idx'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user', 'youtube_data'), name='unique_user_like'),
        ),
    ]
