# Generated by Django 3.1.2 on 2024-12-18 09:44

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeData',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('views', models.BigIntegerField()),
                ('upload_date', models.DateTimeField()),
                ('url', models.URLField(unique=True)),
                ('channel', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, null=True)),
                ('likes', models.BigIntegerField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('comments', djongo.models.fields.ArrayField(blank=True, model_container=account.models.YouTubeComment, null=True)),
                ('transcript', djongo.models.fields.ArrayField(blank=True, default=list, model_container=account.models.Transcript, null=True)),
            ],
            options={
                'db_table': 'youtube_datas',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('youtube_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.youtubedata')),
            ],
            options={
                'unique_together': {('user', 'youtube_data')},
            },
        ),
    ]
