# Generated by Django 3.1.12 on 2024-11-25 11:45

import account.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeData',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('views', models.BigIntegerField()),
                ('upload_date', models.DateTimeField()),
                ('url', models.URLField()),
                ('channel', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, null=True)),
                ('likes', models.BigIntegerField(blank=True, null=True)),
                ('comments', djongo.models.fields.ArrayField(blank=True, model_container=account.models.YouTubeComment, null=True)),
            ],
            options={
                'db_table': 'youtube_datas',
            },
        ),
    ]
