# Generated by Django 3.1.12 on 2024-12-24 01:44

import account.models
import bson.objectid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('chart_date', models.DateTimeField()),
                ('rank', models.IntegerField()),
                ('channel_name', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('views', models.BigIntegerField()),
                ('upload_date', models.DateTimeField()),
                ('url', models.URLField(unique=True)),
                ('channel', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, null=True)),
                ('likes', models.BigIntegerField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('comments', djongo.models.fields.ArrayField(blank=True, default=list, model_container=account.models.YouTubeComment)),
                ('transcript', djongo.models.fields.ArrayField(blank=True, default=list, model_container=account.models.Transcript)),
            ],
            options={
                'db_table': 'chart',
            },
        ),
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('rating', models.PositiveBigIntegerField()),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedbacks',
            },
        ),
    ]
