# Generated by Django 4.1.13 on 2024-11-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_article_content_article_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('views', models.IntegerField()),
                ('upload_date', models.DateTimeField()),
                ('url', models.URLField(max_length=500)),
                ('desc', models.TextField()),
                ('likes', models.IntegerField()),
                ('comments', models.IntegerField()),
            ],
            options={
                'db_table': 'youtube_data_1121_09',
            },
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
