# Generated by Django 3.1.12 on 2024-11-28 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtubedata',
            old_name='id',
            new_name='_id',
        ),
    ]
