# Generated by Django 3.1.12 on 2024-12-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20241128_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubedata',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
