# Generated by Django 4.1.13 on 2024-11-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_youtubevideo_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'youtube_data_1121_18',
            },
        ),
        migrations.DeleteModel(
            name='YouTubeVideo',
        ),
    ]
